### ISSUE TITLE
Unable to launch utility after installing

### ISSUE THREAD

**Issue by YashKumarVerma** [GDGVIT/HandWriter#15]
I installed the utility using [this script](https://raw.githubusercontent.com/GDGVIT/HandWriter/master/install.sh) as was given on [this site](https://handwriter.dscvit.com/installer/linux/)

The utility did not throw any error and exited with a zero exit code. 

However, I am unable to launch the utility.

---

Note that the link is visible in `/usr/local/bin`
![image](https://user-images.githubusercontent.com/14032427/81078919-7693d200-8f0c-11ea-8e6f-4fae5cec2829.png)

However `/opt/ does not have the HandWriter directory`

---
System Info
![image](https://user-images.githubusercontent.com/14032427/81079062-a9d66100-8f0c-11ea-8811-9b0bd74d0d55.png)

**Comment by SaurusXI** [comment]
There was an issue during development that broke some GPG keys. Due to lack of authentication from server side, your package manager prevented the install of the application. 
That has been fixed now, please try rerunning the install script. The issue shouldn't persist.

**Comment by SaurusXI** [comment]
However, the install script throwing a non-zero exit code could be handled better. It seems like an easy enough issue to fix, as only the install shell script needs to be modified. If you'd be interested in adding this functionality to the install.sh script, feel free to make a PR for it on the `dev` branch.
