### ISSUE TITLE
Module not found error in Handwriter.py

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/HandWriter#3]
## Execution steps:
- Cloned the repo and installed all the dependencies
- Ran Handwiter.py using python

## Output/Error

![image](https://user-images.githubusercontent.com/31818185/77368881-3c6ad880-6d83-11ea-8ada-f626718d5a2d.png)

**Comment by SaurusXI** [comment]
I've made a PR that should fix this among other things - #4

**Comment by Geek-ubaid** [comment]
Okay closing the issue its fixed in the latest [PR](#4)
